FROM ubuntu
MAINTAINER Torrie Fischer <torrie@xdv.io>

RUN apt-get update -qq &&\
    apt-get install -qq software-properties-common &&\
    apt-add-repository -y ppa:ubuntu-toolchain-r/test &&\
    apt-add-repository -y ppa:afrank/boost &&\
    apt-get update -qq

RUN apt-get purge -qq libboost1.48-dev &&\
    apt-get install -qq libprotobuf8 libboost1.57-all-dev

RUN mkdir -p /srv/divvyd/data

VOLUME /srv/divvyd/data/

ENTRYPOINT ["/srv/divvyd/bin/divvyd"]
CMD ["--conf", "/srv/divvyd/data/divvyd.cfg"]
EXPOSE 51235/udp
EXPOSE 5005/tcp

ADD ./divvyd.cfg /srv/divvyd/data/divvyd.cfg
ADD ./divvyd /srv/divvyd/bin/
